import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { analyzeIdea } from "../api/ideaApi.js";

const INDUSTRIES = [
  "FoodTech",
  "EdTech",
  "FinTech",
  "HealthTech",
  "E-commerce",
  "SaaS",
  "AI/ML",
  "Logistics",
  "Other",
];
const REGIONS = ["India", "Global", "Southeast Asia", "USA/Canada", "Europe"];
const BUDGETS = ["Low", "Medium", "High"];

export default function Landing() {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    idea: "",
    industry: "FoodTech",
    targetUsers: "",
    region: "India",
    budget: "Medium",
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const update = (key) => (e) => setForm((f) => ({ ...f, [key]: e.target.value }));

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!form.idea.trim()) {
      setError("Describe your idea in a sentence or two first.");
      return;
    }
    setError("");
    setLoading(true);
    try {
      const result = await analyzeIdea(form);
      navigate("/results", { state: { input: form, result } });
    } catch (err) {
      setError(err.message || "Couldn't reach the server. Is the backend running?");
    } finally {
      setLoading(false);
    }
  };

  const tryExample = () => {
    setForm({
      idea: "An AI app that lets small rural shop owners take voice-based orders and manage inventory in their local language.",
      industry: "AI/ML",
      targetUsers: "Small kirana store owners",
      region: "India",
      budget: "Low",
    });
  };

  return (
    <div className="max-w-6xl mx-auto px-6 py-14 lg:py-20">
      {/* Hero */}
      <div className="grid lg:grid-cols-5 gap-12 items-start">
        <div className="lg:col-span-2">
          <p className="eyebrow text-accent2 mb-4">Pitch it. Get the verdict.</p>
          <h1 className="font-display text-4xl lg:text-[2.75rem] leading-[1.1] font-semibold mb-5">
            Every founder thinks their idea is the next big thing.
            <span className="text-muted"> An AI analyst will tell you if it actually is.</span>
          </h1>
          <p className="text-muted mb-8 leading-relaxed">
            Describe your startup idea on the right. In seconds you'll get a market
            score, SWOT analysis, MVP roadmap, competitor map, and an investor-ready
            pitch — generated by an LLM acting as a venture analyst.
          </p>

          <div className="space-y-4">
            {[
              ["01", "Describe", "Tell the analyst your idea, industry, and target users."],
              ["02", "Analyze", "The AI scores it on market size, feasibility, and competition."],
              ["03", "Build", "Walk away with an MVP roadmap and investor pitch."],
            ].map(([n, title, desc]) => (
              <div key={n} className="flex gap-4 items-start">
                <span className="font-mono text-accent text-sm pt-0.5">{n}</span>
                <div>
                  <p className="font-medium">{title}</p>
                  <p className="text-sm text-muted">{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Form card */}
        <div className="lg:col-span-3">
          <form
            onSubmit={handleSubmit}
            className="bg-surface border border-border rounded-2xl p-6 lg:p-8 shadow-glow"
          >
            <div className="flex items-center justify-between mb-5">
              <h2 className="font-display font-semibold text-lg">Submit your idea</h2>
              <button
                type="button"
                onClick={tryExample}
                className="text-xs text-accent2 hover:underline font-mono"
              >
                use an example
              </button>
            </div>

            <label className="block mb-4">
              <span className="text-sm text-muted mb-1.5 block">Startup idea</span>
              <textarea
                value={form.idea}
                onChange={update("idea")}
                rows={4}
                placeholder="e.g. An AI based food delivery app for rural India that..."
                className="w-full bg-surface2 border border-border rounded-lg px-4 py-3 text-sm placeholder:text-muted/60 focus:border-accent outline-none resize-none"
              />
            </label>

            <div className="grid sm:grid-cols-2 gap-4 mb-4">
              <label className="block">
                <span className="text-sm text-muted mb-1.5 block">Industry</span>
                <select
                  value={form.industry}
                  onChange={update("industry")}
                  className="w-full bg-surface2 border border-border rounded-lg px-4 py-2.5 text-sm focus:border-accent outline-none"
                >
                  {INDUSTRIES.map((i) => (
                    <option key={i}>{i}</option>
                  ))}
                </select>
              </label>

              <label className="block">
                <span className="text-sm text-muted mb-1.5 block">Region</span>
                <select
                  value={form.region}
                  onChange={update("region")}
                  className="w-full bg-surface2 border border-border rounded-lg px-4 py-2.5 text-sm focus:border-accent outline-none"
                >
                  {REGIONS.map((r) => (
                    <option key={r}>{r}</option>
                  ))}
                </select>
              </label>

              <label className="block">
                <span className="text-sm text-muted mb-1.5 block">Target users (optional)</span>
                <input
                  value={form.targetUsers}
                  onChange={update("targetUsers")}
                  placeholder="e.g. college students"
                  className="w-full bg-surface2 border border-border rounded-lg px-4 py-2.5 text-sm placeholder:text-muted/60 focus:border-accent outline-none"
                />
              </label>

              <label className="block">
                <span className="text-sm text-muted mb-1.5 block">Budget level</span>
                <select
                  value={form.budget}
                  onChange={update("budget")}
                  className="w-full bg-surface2 border border-border rounded-lg px-4 py-2.5 text-sm focus:border-accent outline-none"
                >
                  {BUDGETS.map((b) => (
                    <option key={b}>{b}</option>
                  ))}
                </select>
              </label>
            </div>

            {error && (
              <p className="text-danger text-sm mb-4 bg-danger/10 border border-danger/30 rounded-lg px-3 py-2">
                {error}
              </p>
            )}

            <button
              type="submit"
              disabled={loading}
              className="w-full bg-accent hover:bg-accent/90 disabled:opacity-60 text-ink font-display font-semibold rounded-lg py-3 transition-colors"
            >
              {loading ? "Analyzing your idea…" : "Get the verdict →"}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}
